---
- name: Ensure project directory exists
  ansible.builtin.file:
    path: "{{ middleware_dir }}"
    state: directory
    mode: '0755'

- name: Copy Middleware source files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ middleware_dir }}/{{ item }}"
    mode: '0644'
  with_items:
    - main.py
    - generate_boxplots.py
    - Dockerfile
    - requirements.txt

- name: Ensure CSV data directory exists
  ansible.builtin.file:
    path: "{{ middleware_dir }}/data"
    state: directory
    mode: '0777'

- name: Render Docker Compose
  ansible.builtin.template:
    src: docker_compose_middleware.yml.j2
    dest: "{{ middleware_dir }}/docker-compose.yml"
    mode: '0644'

- name: Build and Start Middleware
  community.docker.docker_compose_v2:
    project_src: "{{ middleware_dir }}"
    state: present
    build: always  # Erzwingt den Build auf dem Remote-Host

- name: Allow Middleware Port
  community.general.ufw:
    rule: allow
    port: "{{ middleware_port | default(8000) }}"
    proto: tcp
